version: "3.9"

services:

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: always
    networks:
      - main

  app:
    build:
      context: .
    container_name: app
    command: sh -c "python manage.py migrate &&
      python manage.py collectstatic --no-input --clear &&
      gunicorn project.wsgi -b 0.0.0.0:8000"
    volumes:
      - static:/source/static
      - media:/source/media
    depends_on:
      - database
    environment:
      - DEBUG=FALSE
      - ALLOWED_HOSTS=*
      - DATABASE-NAME=postgres
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/var/www/static
      - media:/var/www/media

networks:
  main:

volumes:
  postgres:
  static:
  media:
