# Generated by Django 4.2.3 on 2023-08-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PvMessageModel',
            new_name='MessageModel',
        ),
    ]
