# Generated by Django 4.2.3 on 2023-08-18 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bmembershipmodel",
            old_name="board.py",
            new_name="board",
        ),
        migrations.RenameField(
            model_name="gmessagemodel",
            old_name="board.py",
            new_name="board",
        ),
        migrations.RenameField(
            model_name="listmodel",
            old_name="board.py",
            new_name="board",
        ),
    ]
