# Generated by Django 4.2.3 on 2023-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardmodel",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="prerequisite_cards", to="tasks.cardmodel"
            ),
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="is_independent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cardmodel",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="dependent_cards", to="tasks.cardmodel"
            ),
        ),
        migrations.AlterField(
            model_name="boardmodel",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Enter Board title",
                max_length=100,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="cardmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("doing", "Doing"),
                    ("done", "Done"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cardmodel",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Enter Card title",
                max_length=150,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="labelmodel",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Enter Label title",
                max_length=50,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="listmodel",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Enter List title",
                max_length=100,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="subtaskmodel",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Please enter your sub task title",
                max_length=250,
                verbose_name="Title",
            ),
        ),
    ]
