# Generated by Django 4.2.4 on 2023-08-21 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationAddMemeber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('to_add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relation-add-member',
                'verbose_name_plural': 'relation-add-members',
                'db_table': 'relation-add-member-model',
            },
        ),
    ]
