# Generated by Django 4.2.3 on 2023-08-22 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_relationaddmemeber"),
        ("tasks", "0002_rename_board_py_bmembershipmodel_board_and_more"),
    ]

    operations = []
